### ISSUE TITLE
Add {{nosportssigcov}}?

### ISSUE THREAD

**Issue by TechnoSquirrel69** [wikimedia-gadgets/twinkle#2000] opened 2024-09-04 22:56 UTC
Twinkle does not currently list {{[No significant coverage (sports)](https://en.wikipedia.org/wiki/Template:No_significant_coverage_(sports))}} in the tag module, which may come in handy for editors working in that topic area. The banner currently reads as follows:
![image](https://github.com/user-attachments/assets/b392991f-02a8-4e99-b543-fc5a3ec1e928)
What do we think about including it?

**Comment by NovemLinguae** [comment] 2024-09-04 23:02
Thanks for the idea.

Honestly my first instinct is to TFD this, because it appears to be almost identical to {{No significant coverage}}. I see it was created by BM around when WP:NSPORT was overhauled, so I imagine that is the reason it ended up as its own template.

Anyway, I guess my question is, is there any reason we shouldn't just merge this template with {{No significant coverage}}? Thoughts on that?

By the way, I don't see {{No significant coverage}} in Twinkle, and I'd be open to including that one.

Thanks a lot. Looking forward to your feedback.

**Comment by TechnoSquirrel69** [comment] 2024-09-04 23:14
Yeah, I forgot to check whether the main template was listed — that seems like a very straightforward yes to me. No comment on a TfD for the sports template, but it's worth noting that it differs from the vanilla case of sources lacking significant coverage as it could be a BLP concern. It also populates its own family of maintenance categories. It may also be helpful to get feedback from Thebiguglyalien and asilvering, who were discussing it in the NPP Discord server.

**Comment by NovemLinguae** [comment] 2024-09-04 23:34
I think I'll go ahead and TFD it to get a discussion going onwiki. I think that is the most "by the book" way to discuss something like this.

Let's revisit this ticket once the TFD is concluded.

I've also created #2001 to add {{No significant coverage}}

**Comment by NovemLinguae** [comment] 2024-09-04 23:43
Closing since this is a duplicate of #1817. Let's continue discussion in there.

**Closed by NovemLinguae** 2024-09-04 23:43 UTC
