### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'Twinkle.welcome.normal')

### ISSUE THREAD

**Issue by jdlrobson** [wikimedia-gadgets/twinkle#2093] opened 2024-12-02 22:20 UTC
Any idea what might be causing this error in production? 1,089 errors in last 7 days

I was unable to replicate it on https://en.m.wikipedia.org/wiki/Esther_Hart_(Titanic_survivor) but all the errors come from mobile domain with the following gadgets enabled:

Twinkle,morebits,select2,geonotice,defaultsummaries,HotCat,afchelper,switcher,script-installer,Twinkle-pagestyles

and the stack trace is pretty useless but flags the offending function as:
```
at twinklewelcome 
```
Presumably when that method is executed, Twinkle.welcome.normal doesn't exist ?

**Comment by NovemLinguae** [comment] 2024-12-02 22:30
I did a deploy that fixed some bugs 3 days ago. Any chance the errors stopped 3 days ago?

**Comment by NovemLinguae** [comment] 2024-12-02 22:39
I renamed some of that stuff from friendlywelcome to twinklewelcome about 2 weeks ago.

https://github.com/NovemLinguae/twinkle/commit/35efcd882b15e9c603a3489e812817113f004a25

Do we have the exact date the errors started, so I can track down which deploy is the cause?

Also, any suggestions for mw.log type code to add to get us better info?

**Comment by nardog** [comment] 2024-12-02 22:44
Might have to do with [TwinkleMobile](https://en.wikipedia.org/wiki/User:Plantaest/TwinkleMobile).

**Comment by NovemLinguae** [comment] 2024-12-02 22:52
Nice catch. Yeah regular Twinkle doesn't even work with Minerva. I should have thought of that. I've pinged the TwinkleMobile maintainer onwiki: https://en.wikipedia.org/wiki/User_talk:Plantaest/TwinkleMobile#Changes_to_upstream_Twinkle

**Comment by jdlrobson** [comment] 2024-12-11 00:37
Can confirm that https://vi.wikipedia.org/w/index.php?title=Th%C3%A0nh_vi%C3%AAn:Plantaest/TwinkleMobile.js was the problem.

**Comment by NovemLinguae** [comment] 2024-12-11 00:45
Sounds like this is downstream. Closing. Although feel free to keep commenting in this thread if communication here is easier.

**Closed by NovemLinguae** 2024-12-11 00:45 UTC
